### PR TITLE
feat: add scripts for hwinit and eth0 MAC address

### PR DESCRIPTION
**Pull request by shodan8192**
This commit adds scripts :
- `store_eth0_mac` which saves first boot eth0 MAC to config
- `S10hwinit` which calls `duo-init.sh`, sets eth0 MAC from config, and run USB with selected function

`S99user` is now used only to call user application.

### CODE REVIEW

**Review by gtxzsxxk — APPROVED** [review]
Looks good to me. I will merge this this weekend. Thanks for contribution!

**Comment by shodan8192** [comment]
I've renamed scripts, it doesn't matter much yet, but it'll after changes i'm preparing.

**Comment by gtxzsxxk** [comment]
OK I be back. Let me take a look on this

**Review by gtxzsxxk — APPROVED** [review]
Pretty nice. Let me merge this. Sorry for the delay.

**Pull request merged**
